name: andreawheir
favicon: null
layout_spectrum: 0.5035995577927679
typography_spectrum: 0.27416288550011814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7685817913152277
  lightness: 0.15506649645976722
  saturation: 0.6222931847441941
  rhythmicContrast: 0.03758553834632039
purpose: []
